name: Generate Implementation Issues

on:
  workflow_dispatch:
    inputs:
      phase:
        description: 'Implementation phase to generate issues for (0-6)'
        required: true
        default: '0'
        type: choice
        options:
        - '0'
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
        - '6'

# Request necessary permissions
permissions:
  issues: write
  repository-projects: write
  contents: read
  
jobs:
  generate-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile @octokit/rest
      
      - name: Debug Implementation Plan structure
        run: |
          echo "Implementation Plan Content Preview:"
          head -n 50 docs/72-implementation-Plan.md
          echo "..."
          grep -n "Phase 0" docs/72-implementation-Plan.md || echo "No matches for Phase 0"
          grep -n "### Phase" docs/72-implementation-Plan.md || echo "No matches for ### Phase"
      
      - name: Generate issues
        run: node scripts/generate-issues.js ${{ github.event.inputs.phase }} ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
